blank_issues_enabled: true
contact_links:
  - name: Official Argentable Support
    url: argentable@gmail.com
    about: Please ask and answer questions here.
  - name: Argentable Twitter
    url: https://twitter.com/Argentable
    about: Post security concerns and feature requests here.
  - name: Individual Developers
    url: aerialconnection98@gmail.com
